### PR TITLE
Disabled deprecation warnings.

### PR DESCRIPTION
**Pull request by dmcconachie**
This makes it easier to catch problems in other packages, but it does have the potential of missing problems later. Still, I think it's worth it.

### CODE REVIEW

**Comment by LinYuChi** [comment]
I do not recall what the deprecated function is. Can you give me a hint? thanks.

**Comment by dmcconachie** [comment]
Things are marked as deprecated by developers as a way to indicate that that function/type/whatever is an old version that has been replaced by something else, and users should start migrating to the new way of doing things. I.e.
```
virtual void ViewerSetSize(int w, int h) RAVE_DEPRECATED { ... }
```

**Comment by LinYuChi** [comment]
Ugh... I mean I do not recall what is the name of the deprecated functions. Anyway, I get it. I think I saw this before. Thanks.

**Review by LinYuChi — APPROVED** [review]

**Comment by dmcconachie** [comment]
Oh, I see. Um, many many of them. The particular warning I'm suppressing is about the `TPOINT` type I believe.

**Comment by dmcconachie** [comment]
```
In file included from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:187:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:35:
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.h:53:72: warning: ‘OpenRAVE::TrajectoryBase::TPOINT’ is deprecated [-Wdeprecated-declarations]
     void OptimizePathRandomized(RobotBasePtr probot, list< Trajectory::TPOINT >& path, const vector<dReal>& qresolutioninv, int nMaxIterations);
                                                                        ^
In file included from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/trajectory.h:195:26: note: declared here
     typedef Point TPOINT RAVE_DEPRECATED;
                          ^
In file included from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:187:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:35:
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.h:54:65: warning: ‘OpenRAVE::TrajectoryBase::TPOINT’ is deprecated [-Wdeprecated-declarations]
     void OptimizePathAll(RobotBasePtr probot, list< Trajectory::TPOINT >& path, const vector<dReal>& qresolutioninv);
                                                                 ^
In file included from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/trajectory.h:195:26: note: declared here
     typedef Point TPOINT RAVE_DEPRECATED;
                          ^
In file included from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:187:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:35:
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.h:65:50: warning: ‘TPOINT’ is deprecated [-Wdeprecated-declarations]
   JointPos(const OpenRAVE::Trajectory::TPOINT &tp) : 
                                                  ^
In file included from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:187:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:35:
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.h:53:72: warning: ‘OpenRAVE::TrajectoryBase::TPOINT’ is deprecated [-Wdeprecated-declarations]
     void OptimizePathRandomized(RobotBasePtr probot, list< Trajectory::TPOINT >& path, const vector<dReal>& qresolutioninv, int nMaxIterations);
                                                                        ^
In file included from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/trajectory.h:195:26: note: declared here
     typedef Point TPOINT RAVE_DEPRECATED;
                          ^
In file included from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:187:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:35:
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.h:54:65: warning: ‘OpenRAVE::TrajectoryBase::TPOINT’ is deprecated [-Wdeprecated-declarations]
     void OptimizePathAll(RobotBasePtr probot, list< Trajectory::TPOINT >& path, const vector<dReal>& qresolutioninv);
                                                                 ^
In file included from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/trajectory.h:195:26: note: declared here
     typedef Point TPOINT RAVE_DEPRECATED;
                          ^
In file included from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:187:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:35:
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.h:65:50: warning: ‘TPOINT’ is deprecated [-Wdeprecated-declarations]
   JointPos(const OpenRAVE::Trajectory::TPOINT &tp) : 
                                                  ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp: In member function ‘bool TrajectoryProblem::VerifyTraj(std::ostream&, std::istream&)’:
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:234:29: warning: ‘OpenRAVE::TrajectoryBase::TPOINT’ is deprecated [-Wdeprecated-declarations]
     std::vector<Trajectory::TPOINT> path;
                             ^
In file included from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/trajectory.h:195:26: note: declared here
     typedef Point TPOINT RAVE_DEPRECATED;
                          ^
In file included from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:35:0:
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:235:39: warning: ‘virtual const std::vector<OpenRAVE::TrajectoryBase::Point>& OpenRAVE::TrajectoryBase::GetPoints() const’ is deprecated [-Wdeprecated-declarations]
     FOREACH(itpoint, ptraj->GetPoints())
                                       ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:167:36: note: in definition of macro ‘FOREACH’
 #define FOREACH(it, v) for(typeof((v).begin()) it = (v).begin(); it != (v).end(); (it)++)
                                    ^
In file included from /home/dmcconac/local/include/openrave-0.9/openrave/openrave.h:2245:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/trajectory.h:201:39: note: declared here
     virtual const std::vector<Point>& GetPoints() const RAVE_DEPRECATED;
                                       ^
In file included from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:35:0:
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:235:39: warning: ‘virtual const std::vector<OpenRAVE::TrajectoryBase::Point>& OpenRAVE::TrajectoryBase::GetPoints() const’ is deprecated [-Wdeprecated-declarations]
     FOREACH(itpoint, ptraj->GetPoints())
                                       ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:167:54: note: in definition of macro ‘FOREACH’
 #define FOREACH(it, v) for(typeof((v).begin()) it = (v).begin(); it != (v).end(); (it)++)
                                                      ^
In file included from /home/dmcconac/local/include/openrave-0.9/openrave/openrave.h:2245:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/trajectory.h:201:39: note: declared here
     virtual const std::vector<Point>& GetPoints() const RAVE_DEPRECATED;
                                       ^
In file included from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:35:0:
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:235:39: warning: ‘virtual const std::vector<OpenRAVE::TrajectoryBase::Point>& OpenRAVE::TrajectoryBase::GetPoints() const’ is deprecated [-Wdeprecated-declarations]
     FOREACH(itpoint, ptraj->GetPoints())
                                       ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:167:73: note: in definition of macro ‘FOREACH’
 #define FOREACH(it, v) for(typeof((v).begin()) it = (v).begin(); it != (v).end(); (it)++)
                                                                         ^
In file included from /home/dmcconac/local/include/openrave-0.9/openrave/openrave.h:2245:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/trajectory.h:201:39: note: declared here
     virtual const std::vector<Point>& GetPoints() const RAVE_DEPRECATED;
                                       ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp: In member function ‘virtual bool TrajectoryProblem::BlendTrajectory(std::ostream&, std::istream&)’:
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:391:65: warning: ‘virtual int OpenRAVE::TrajectoryBase::GetInterpMethod() const’ is deprecated [-Wdeprecated-declarations]
       pnewtraj->CalcTrajTiming(robot, pnewtraj->GetInterpMethod(), true, false); //this retiming is just for playback using idealcontroller
                                                                 ^
In file included from /home/dmcconac/local/include/openrave-0.9/openrave/openrave.h:2245:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/trajectory.h:227:17: note: declared here
     virtual int GetInterpMethod() const RAVE_DEPRECATED {
                 ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:391:79: warning: ‘virtual bool OpenRAVE::TrajectoryBase::CalcTrajTiming(OpenRAVE::RobotBasePtr, int, bool, bool, OpenRAVE::dReal)’ is deprecated [-Wdeprecated-declarations]
       pnewtraj->CalcTrajTiming(robot, pnewtraj->GetInterpMethod(), true, false); //this retiming is just for playback using idealcontroller
                                                                               ^
In file included from /home/dmcconac/local/include/openrave-0.9/openrave/openrave.h:2245:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/trajectory.h:232:18: note: declared here
     virtual bool CalcTrajTiming(RobotBasePtr probot, int interp,  bool autocalc, bool activedof, dReal fmaxvelmult=1) RAVE_DEPRECATED;
                  ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp: In member function ‘int ManipulationProblem::SetActiveManip(std::istream&)’:
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:936:42: warning: ‘virtual void OpenRAVE::RobotBase::SetActiveManipulator(int)’ is deprecated [-Wdeprecated-declarations]
             robot->SetActiveManipulator(4);
                                          ^
In file included from /home/dmcconac/local/include/openrave-0.9/openrave/openrave.h:2249:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/robot.h:764:18: note: declared here
     virtual void SetActiveManipulator(int index) RAVE_DEPRECATED;
                  ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:941:42: warning: ‘virtual void OpenRAVE::RobotBase::SetActiveManipulator(int)’ is deprecated [-Wdeprecated-declarations]
             robot->SetActiveManipulator(3);
                                          ^
In file included from /home/dmcconac/local/include/openrave-0.9/openrave/openrave.h:2249:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/robot.h:764:18: note: declared here
     virtual void SetActiveManipulator(int index) RAVE_DEPRECATED;
                  ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:946:42: warning: ‘virtual void OpenRAVE::RobotBase::SetActiveManipulator(int)’ is deprecated [-Wdeprecated-declarations]
             robot->SetActiveManipulator(1);
                                          ^
In file included from /home/dmcconac/local/include/openrave-0.9/openrave/openrave.h:2249:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/robot.h:764:18: note: declared here
     virtual void SetActiveManipulator(int index) RAVE_DEPRECATED;
                  ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:951:42: warning: ‘virtual void OpenRAVE::RobotBase::SetActiveManipulator(int)’ is deprecated [-Wdeprecated-declarations]
             robot->SetActiveManipulator(2);
                                          ^
In file included from /home/dmcconac/local/include/openrave-0.9/openrave/openrave.h:2249:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/robot.h:764:18: note: declared here
     virtual void SetActiveManipulator(int index) RAVE_DEPRECATED;
                  ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:956:42: warning: ‘virtual void OpenRAVE::RobotBase::SetActiveManipulator(int)’ is deprecated [-Wdeprecated-declarations]
             robot->SetActiveManipulator(0);
                                          ^
In file included from /home/dmcconac/local/include/openrave-0.9/openrave/openrave.h:2249:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/robot.h:764:18: note: declared here
     virtual void SetActiveManipulator(int index) RAVE_DEPRECATED;
                  ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:964:48: warning: ‘virtual void OpenRAVE::RobotBase::SetActiveManipulator(int)’ is deprecated [-Wdeprecated-declarations]
                 robot->SetActiveManipulator(ind);
                                                ^
In file included from /home/dmcconac/local/include/openrave-0.9/openrave/openrave.h:2249:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/robot.h:764:18: note: declared here
     virtual void SetActiveManipulator(int index) RAVE_DEPRECATED;
                  ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp: In member function ‘int ManipulationProblem::MoveManipulator(std::istream&)’:
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:1011:42: warning: ‘virtual void OpenRAVE::RobotBase::SetActiveManipulator(int)’ is deprecated [-Wdeprecated-declarations]
             robot->SetActiveManipulator(1);
                                          ^
In file included from /home/dmcconac/local/include/openrave-0.9/openrave/openrave.h:2249:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/robot.h:764:18: note: declared here
     virtual void SetActiveManipulator(int index) RAVE_DEPRECATED;
                  ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:1016:42: warning: ‘virtual void OpenRAVE::RobotBase::SetActiveManipulator(int)’ is deprecated [-Wdeprecated-declarations]
             robot->SetActiveManipulator(2);
                                          ^
In file included from /home/dmcconac/local/include/openrave-0.9/openrave/openrave.h:2249:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/robot.h:764:18: note: declared here
     virtual void SetActiveManipulator(int index) RAVE_DEPRECATED;
                  ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:1021:42: warning: ‘virtual void OpenRAVE::RobotBase::SetActiveManipulator(int)’ is deprecated [-Wdeprecated-declarations]
             robot->SetActiveManipulator(0);
                                          ^
In file included from /home/dmcconac/local/include/openrave-0.9/openrave/openrave.h:2249:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/robot.h:764:18: note: declared here
     virtual void SetActiveManipulator(int index) RAVE_DEPRECATED;
                  ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp: At global scope:
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:649:87: warning: ‘OpenRAVE::TrajectoryBase::TPOINT’ is deprecated [-Wdeprecated-declarations]
 void TrajectoryProblem::OptimizePathRandomized(RobotBasePtr probot, list< Trajectory::TPOINT >& path, const vector<dReal>& qresolutioninv, int nMaxIterations)
                                                                                       ^
In file included from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/trajectory.h:195:26: note: declared here
     typedef Point TPOINT RAVE_DEPRECATED;
                          ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp: In member function ‘void TrajectoryProblem::OptimizePathRandomized(OpenRAVE::RobotBasePtr, std::__cxx11::list<OpenRAVE::TrajectoryBase::Point>&, const std::vector<double>&, int)’:
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:654:23: warning: ‘OpenRAVE::TrajectoryBase::TPOINT’ is deprecated [-Wdeprecated-declarations]
     list< Trajectory::TPOINT >::iterator itstart, itend;
                       ^
In file included from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/trajectory.h:195:26: note: declared here
     typedef Point TPOINT RAVE_DEPRECATED;
                          ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp: At global scope:
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:689:80: warning: ‘OpenRAVE::TrajectoryBase::TPOINT’ is deprecated [-Wdeprecated-declarations]
 void TrajectoryProblem::OptimizePathAll(RobotBasePtr probot, list< Trajectory::TPOINT >& path, const vector<dReal>& qresolutioninv)
                                                                                ^
In file included from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/trajectory.h:195:26: note: declared here
     typedef Point TPOINT RAVE_DEPRECATED;
                          ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp: In member function ‘void TrajectoryProblem::OptimizePathAll(OpenRAVE::RobotBasePtr, std::__cxx11::list<OpenRAVE::TrajectoryBase::Point>&, const std::vector<double>&)’:
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:691:23: warning: ‘OpenRAVE::TrajectoryBase::TPOINT’ is deprecated [-Wdeprecated-declarations]
     list< Trajectory::TPOINT >::iterator itstart = path.begin();
                       ^
In file included from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/trajectory.h:195:26: note: declared here
     typedef Point TPOINT RAVE_DEPRECATED;
                          ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:694:27: warning: ‘OpenRAVE::TrajectoryBase::TPOINT’ is deprecated [-Wdeprecated-declarations]
         list< Trajectory::TPOINT >::iterator itend = path.end();
                           ^
In file included from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/trajectory.h:195:26: note: declared here
     typedef Point TPOINT RAVE_DEPRECATED;
                          ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:698:35: warning: ‘OpenRAVE::TrajectoryBase::TPOINT’ is deprecated [-Wdeprecated-declarations]
                 list< Trajectory::TPOINT >::iterator itnext = itstart;
                                   ^
In file included from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/trajectoryproblem.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/trajectory.h:195:26: note: declared here
     typedef Point TPOINT RAVE_DEPRECATED;
                          ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp: In member function ‘std::vector<double> ManipulationProblem::LiftArmGeneralIK(std::istream&)’:
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:1726:61: warning: ‘virtual int OpenRAVE::RobotBase::GetActiveManipulatorIndex() const’ is deprecated [-Wdeprecated-declarations]
         ikparams.push_back(robot->GetActiveManipulatorIndex()); //index of this manipulator
                                                             ^
In file included from /home/dmcconac/local/include/openrave-0.9/openrave/openrave.h:2249:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/robot.h:789:17: note: declared here
     virtual int GetActiveManipulatorIndex() const RAVE_DEPRECATED;
                 ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp: In member function ‘std::vector<double> ManipulationProblem::InterpolateToEEPose(std::istream&)’:
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:1922:61: warning: ‘virtual int OpenRAVE::RobotBase::GetActiveManipulatorIndex() const’ is deprecated [-Wdeprecated-declarations]
         ikparams.push_back(robot->GetActiveManipulatorIndex()); //index of this manipulator
                                                             ^
In file included from /home/dmcconac/local/include/openrave-0.9/openrave/openrave.h:2249:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/robot.h:789:17: note: declared here
     virtual int GetActiveManipulatorIndex() const RAVE_DEPRECATED;
                 ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp: In member function ‘std::vector<double> ManipulationProblem::GetWristPoints(std::istream&)’:
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:2034:84: warning: ‘OpenRAVE::TrajectoryBasePtr OpenRAVE::RaveCreateTrajectory(OpenRAVE::EnvironmentBasePtr, int)’ is deprecated [-Wdeprecated-declarations]
         TrajectoryBasePtr pfulltraj = RaveCreateTrajectory(GetEnv(),robot->GetDOF());
                                                                                    ^
In file included from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/openrave.h:2417:32: note: declared here
 OPENRAVE_API TrajectoryBasePtr RaveCreateTrajectory(EnvironmentBasePtr env, int dof) RAVE_DEPRECATED;
                                ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:2035:60: warning: ‘void OpenRAVE::RobotBase::GetFullTrajectoryFromActive(OpenRAVE::TrajectoryBasePtr, OpenRAVE::TrajectoryBaseConstPtr, bool)’ is deprecated [-Wdeprecated-declarations]
         robot->GetFullTrajectoryFromActive(pfulltraj, ptraj);
                                                            ^
In file included from /home/dmcconac/local/include/openrave-0.9/openrave/openrave.h:2249:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/robot.h:920:10: note: declared here
     void GetFullTrajectoryFromActive(TrajectoryBasePtr pfulltraj, TrajectoryBaseConstPtr pActiveTraj, bool bOverwriteTransforms=true) RAVE_DEPRECATED;
          ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp: In member function ‘int ManipulationProblem::SwitchModelsInternal(std::vector<std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > >&, bool)’:
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:3009:55: warning: ‘virtual void OpenRAVE::EnvironmentBase::AddKinBody(OpenRAVE::KinBodyPtr, bool)’ is deprecated [-Wdeprecated-declarations]
                     GetEnv()->AddKinBody(pfatbody,true);
                                                       ^
In file included from /home/dmcconac/local/include/openrave-0.9/openrave/openrave.h:2256:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/environment.h:393:18: note: declared here
     virtual void AddKinBody(KinBodyPtr body, bool bAnonymous=false) RAVE_DEPRECATED {
                  ^
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp: In member function ‘int ManipulationProblem::MakeGraspTrajectory(std::__cxx11::string&, std::istream&)’:
/home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:4009:46: warning: ‘const std::vector<double>& OpenRAVE::RobotBase::Manipulator::GetClosingDirection() const’ is deprecated [-Wdeprecated-declarations]
     closingdir = pmanip->GetClosingDirection();
                                              ^
In file included from /home/dmcconac/local/include/openrave-0.9/openrave/openrave.h:2249:0,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/stdafx.h:178,
                 from /home/dmcconac/Dropbox/catkin_ws/src/openrave_tools/comps/manipulation2/manipulation.cpp:35:
/home/dmcconac/local/include/openrave-0.9/openrave/robot.h:160:42: note: declared here
         inline const std::vector<dReal>& GetClosingDirection() const RAVE_DEPRECATED {
```

**Comment by LinYuChi** [comment]
Unless openrave will have some significant update in the future (which is unlikely), I do not think we need to change those deprecated functions. A working code is a good code for something quite static like comps.

**Pull request merged**
